version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run:
          name: Get debug resources
          command: |
            mkdir -p app/src/debug/res/values
            echo $GOOGLE_SERVICES_JSON > app/src/debug/google-services.json
            echo $GOOGLE_MAPS_API_KEY > app/src/debug/google_maps_api.xml
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: build apks
          command: ./gradlew assembleDebug assembleDebugAndroidTest
      - persist_to_workspace:
          root: app/build/outputs/apk/
          paths:
            - debug/*.apk
            - androidTest/debug/*.apk

  unit_test:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run:
          name: Get debug resources
          command: |
            mkdir -p app/src/debug/res/values
            echo $GOOGLE_SERVICES_JSON > app/src/debug/google-services.json
            echo $GOOGLE_MAPS_API_KEY > app/src/debug/res/values/google_maps_api.xml
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Unit tests
          command: ./gradlew testDebugUnitTest
      - store_artifacts:
          path: app/build/reports
          destination: reports

  firebase_test:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    steps:
      - attach_workspace:
          at: apk
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            sudo gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: Test with Firebase Test Lab
          command: |
            sudo gcloud firebase test android run \
              --type instrumentation \
              --app apk/debug/app-debug.apk \
              --test apk/androidTest/debug/app-debug-androidTest.apk \
              --device model=Nexus6,version=23,orientation=portrait \
              --device model=Nexus6,version=24,orientation=portrait \
              --device model=Nexus6,version=25,orientation=portrait \
              --device model=sailfish,version=28,orientation=portrait
      - run:
          name: Install gsutil dependency and copy test results data
          command: |
            mkdir -p firebase
            sudo pip install -U crcmod
            sudo gsutil -m cp -r -U `sudo gsutil ls gs://test-lab-fbam099tx55hs-iixxcrt21m42m | tail -1` ~/code/firebase/ | true
      - store_artifacts:
          path: firebase/
          destination: results

workflows:
  version: 2

  default:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - firebase_test:
          requires:
            - build
          filters:
            branches:
              only:
              - master
              - testing